import "./globals.css";
import { Nunito } from "next/font/google";
import { SidebarProvider } from "#/context/sidebarContext";
import "react-loading-skeleton/dist/skeleton.css";

const font = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${font.className}`}>
      <SidebarProvider>
        <body className="h-screen w-screen overflow-hidden flex flex-col flex-nowrap bg-slate-300 dark:bg-slate-900">
          <div className="flex-1 flex flex-row flex-nowrap overflow-hidden">
            {children}
          </div>
        </body>
      </SidebarProvider>
    </html>
  );
}
