import './globals.css';
import { Nunito } from 'next/font/google';
import ServerSidebar from '#/ui/layout/server/Sidebar';
import { SidebarProvider } from '#/context/sidebarContext';

const font = Nunito({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${font.className} dark`}>
      <SidebarProvider>
        <body className="h-screen w-screen overflow-hidden flex flex-col flex-nowrap bg-slate-300 dark:bg-slate-900">
          <div className="flex-1 flex flex-row flex-nowrap overflow-hidden">
            {children}
          </div>
        </body>
      </SidebarProvider>
    </html>
  );
}
